name: "Install cloudflared"
description: "Install cloudflared on workflows"

inputs:
  args:
    description: "no"
    required: true

runs:
  using: "composite"
  steps: 
    - name: download cloudflared
      shell: bash
      run: |
          wget -q https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          cloudflared --version
          rm -rf cloudflared-stable-linux-amd64.deb

    - name: run cloudflared
      shell: bash
      run: cloudflared ${{ inputs.args }}
