name: "Install cloudflared"
description: "Install cloudflared on workflows"

inputs:
  args:
    required: true

runs:
  using: "composite"
  steps: 
    - name: download cloudflared
      shell: bash
      run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          sudo cloudflared update &
          rm -rf cloudflared-linux-amd64.deb
          echo "/ cloudflared install complete! /"
          

    - name: run cloudflared
      shell: bash
      run: |
          echo "/ run cloudflared! /"
          sudo cloudflared ${{ inputs.args }}
